searchSpaceFile: CF_DL_search_space.json
trialCommand: python3 CF_DL.py
trialGpuNumber: 0
trialConcurrency: 8
maxTrialNumber: 800
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
