searchSpaceFile: PMF_search_space.json
trialCommand: python3 PMF.py
trialGpuNumber: 0
trialConcurrency: 8
maxTrialNumber: 300
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
